# Config for default_processor
health_check_port: 8088
server_config:
  processor_config:
    type: default_processor
    channel_size: 100
  transaction_stream_config:
    indexer_grpc_data_service_address: "http://127.0.0.1:50051"
    auth_token: "AUTH_TOKEN"
    request_name_header: "default_processor"
  processor_mode:
    type: "default"
    initial_starting_version: 0
  db_config:
    type: postgres_config
    connection_string: postgresql://aptos:aptos123@localhost:5432/aptos_indexer