# This is a template config.yaml for a processor
health_check_port: 8085
server_config:
  processor_config:
    type: fungible_asset_processor
    channel_size: 100
  transaction_stream_config:
    indexer_grpc_data_service_address: "http://127.0.0.1:50051"
    auth_token: "AUTH_TOKEN"
    request_name_header: "fungible_asset_processor"
  processor_mode:
    type: "default" # Default mode is used to bootstrap the processor from an initial starting version. For backfills, use backfill mode.
    initial_starting_version: 0
  db_config:
    type: postgres_config
    connection_string: postgresql://postgres:@localhost:5433/indexer_v2